# Generated by Django 4.2.1 on 2023-05-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('EmployeeID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('Addres', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('NumberVacation', models.CharField(max_length=100)),
                ('NumberApprovedVacation', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=8)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('MARITALSTATUE', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=8)),
            ],
        ),
    ]
