# Generated by Django 4.2.1 on 2023-05-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredVacationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VFName', models.CharField(max_length=50)),
                ('VFID', models.CharField(max_length=50)),
                ('VFFromDate', models.DateField()),
                ('VFToDate', models.DateField()),
                ('VFReason', models.TextField()),
                ('VFStatus', models.CharField(max_length=15)),
            ],
        ),
    ]
