# Generated by Django 4.2.1 on 2023-05-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_vacationform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationform',
            old_name='fromDate',
            new_name='VFFromDate',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='ID',
            new_name='VFID',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='name',
            new_name='VFName',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='reason',
            new_name='VFReason',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='status',
            new_name='VFStatus',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='toDate',
            new_name='VFToDate',
        ),
    ]
