# Generated by Django 4.2.1 on 2023-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_rename_fromdate_vacationform_vffromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationform',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationform',
            name='VFID',
            field=models.CharField(max_length=50),
        ),
    ]
