# Generated by Django 4.2.1 on 2023-05-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_rename_fromdate_vacationform_vffromdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationform',
            old_name='VFID',
            new_name='EmployeeID',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='VFName',
            new_name='EmployeeName',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='VFFromDate',
            new_name='FromDate',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='VFReason',
            new_name='Reason',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='VFStatus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='VFToDate',
            new_name='ToDate',
        ),
    ]
