# Generated by Django 4.2.1 on 2023-06-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_alter_registerform_numberapprovedvacation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvacationform',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.registerform'),
        ),
        migrations.AddField(
            model_name='registeredvacationform',
            name='vacation_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registeredvacationform',
            name='VFID',
            field=models.IntegerField(null=True),
        ),
    ]
