# Generated by Django 4.2.1 on 2023-06-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_registeredvacationform_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredvacationform',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='registeredvacationform',
            name='vacation_duration',
        ),
        migrations.AlterField(
            model_name='registeredvacationform',
            name='VFID',
            field=models.CharField(max_length=50),
        ),
    ]
