# Generated by Django 4.2.1 on 2023-05-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_vacationform_id_alter_vacationform_vfid'),
        ('HR', '0005_rename_employeename_vacationform_empname'),
    ]

    operations = [
    ]
