# Generated by Django 4.2.1 on 2023-05-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_merge_20230526_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationform',
            old_name='FromDate',
            new_name='VFFromDate',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='EmpName',
            new_name='VFName',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='Reason',
            new_name='VFReason',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='Status',
            new_name='VFStatus',
        ),
        migrations.RenameField(
            model_name='vacationform',
            old_name='ToDate',
            new_name='VFToDate',
        ),
        migrations.RemoveField(
            model_name='vacationform',
            name='EmployeeID',
        ),
    ]
