# Generated by Django 4.2.1 on 2023-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_rename_fromdate_vacationform_vffromdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationform',
            name='id',
        ),
        migrations.AlterField(
            model_name='vacationform',
            name='VFID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
