# Generated by Django 4.2.1 on 2023-05-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_remove_vacationform_id_alter_vacationform_vfid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationform',
            old_name='VFID',
            new_name='id',
        ),
    ]
